"""
Zorya — LangGraph Agent State
==============================
Defines the shared state TypedDict that flows through every node in the
Zorya multi-agent LangGraph pipeline.

Pipeline topology (Sprint 1 target):
  [Parsing Agent] → [Ethical Guardrail Node] → [Clinical CBT Agent] → [Proactive Prompt Agent]

State is persisted across sessions using LangGraph's SQLite checkpointer
(configured in ZOR-7). All fields use `Annotated` reducers so that nodes
can safely append to lists without overwriting each other's writes.
"""

from __future__ import annotations

from typing import Annotated, Optional
import operator
from langgraph.graph import MessagesState


class AgentState(MessagesState):
    """
    Shared state for the Zorya LangGraph multi-agent graph.

    Inherits `messages: list[BaseMessage]` from MessagesState with the
    default `add_messages` reducer (appends, never overwrites).

    All fields below are populated incrementally as the graph traverses nodes.
    """

    # ── User Input ─────────────────────────────────────────────────────────────
    user_birth_date: Optional[str]        # "YYYY-MM-DD" (UTC)
    user_birth_time: Optional[str]        # "HH:MM" (UTC)
    user_latitude: Optional[float]        # Geographic latitude
    user_longitude: Optional[float]       # Geographic longitude
    user_goal: Optional[str]             # User's stated daily self-improvement goal

    # ── Parsing Agent Output ───────────────────────────────────────────────────
    # Raw telemetry from the Celestial MCP tool (as a serialized dict)
    transit_data: Optional[dict]

    # ── Ethical Guardrail Node ─────────────────────────────────────────────────
    # True if content passed guardrail checks; False triggers a safe fallback
    guardrail_passed: Optional[bool]
    guardrail_flags: Annotated[list[str], operator.add]  # Flagged phrases/violations

    # ── Clinical CBT Agent Output ──────────────────────────────────────────────
    # CBT day plan from the Clinical MCP tool (as a serialized dict)
    cbt_plan: Optional[dict]

    # ── Proactive Prompt Agent ─────────────────────────────────────────────────
    # Accountability check-in messages generated by the proactive loop
    proactive_prompts: Annotated[list[str], operator.add]

    # ── Session Metadata ───────────────────────────────────────────────────────
    session_id: Optional[str]
    error: Optional[str]   # Populated if any node encounters a recoverable error
